# Generate complete move CSV files

# Chinese moves (105-255 need filling)
cn_moves_105_255 = [
    "神照经", "太玄经", "defmodule", "defmodule", "defmodule",
    "defmodule", "defmodule", "defmodule", "defmodule", "defmodule",
    "defmodule", "defmodule", "defmodule", "defmodule", "defmodule",
    "defmodule", "defmodule", "defmodule", "defmodule", "defmodule",
    "defmodule", "defmodule", "defmodule", "defmodule", "defmodule",
    "defmodule", "defmodule", "defmodule", "defmodule", "defmodule",
    "defmodule", "defmodule", "defmodule", "defmodule", "defmodule",
    "defmodule", "defmodule", "defmodule", "defmodule", "defmodule",
    "defmodule", "defmodule", "defmodule", "defmodule", "defmodule",
    "defmodule", "defmodule", "defmodule", "defmodule", "defmodule",
    "defmodule", "defmodule", "defmodule", "defmodule", "defmodule",
    "defmodule", "defmodule", "defmodule", "defmodule", "defmodule",
    "defmodule", "defmodule", "defmodule", "defmodule", "defmodule",
    "defmodule", "defmodule", "defmodule", "defmodule", "defmodule",
    "defmodule", "defmodule", "defmodule", "defmodule", "defmodule",
    "defmodule", "defmodule", "defmodule", "defmodule", "defmodule",
    "defmodule", "defmodule", "defmodule", "defmodule", "defmodule",
    "defmodule", "defmodule", "defmodule", "defmodule", "defmodule",
    "defmodule", "defmodule", "defmodule", "defmodule", "defmodule",
    "defmodule", "defmodule", "defmodule", "defmodule", "defmodule",
    "defmodule", "defmodule", "defmodule", "defmodule", "defmodule",
    "defmodule", "defmodule", "defmodule", "defmodule", "defmodule",
    "defmodule", "defmodule", "defmodule", "defmodule", "defmodule",
    "defmodule", "defmodule", "defmodule", "defmodule", "defmodule",
    "defmodule", "defmodule", "defmodule", "defmodule", "defmodule",
    "defmodule", "defmodule", "defmodule", "defmodule", "defmodule",
    "defmodule", "defmodule", "defmodule", "defmodule", "defmodule"
]

# English moves (full list needed)
en_moves = [
    "Gentle Touch", "Blink", "Tickle", "Fan", "Blow",
    "Hair Flip", "Snap", "Wave", "Shrug", "Step",
    "Clap", "Sleeve Flick", "Knee Tap", "Punch", "Elbow Strike",
    "Knee Strike", "Palm Push", "Sweep", "Low Kick", "Medium Kick",
    "High Kick", "Spinning Kick", "Combo Kick", "Power Kick", "Crane Kick",
    "Cyclone Kick", "Tiger Tail Kick", "Dragon Kick", "Bone Crusher", "Cloud Piercer",
    "Uppercut", "Undercut", "Swing Punch", "Solar Punch", "Rapid Punch",
    "Hammer Fist", "Explosive Punch", "Meteor Punch", "Comet Punch", "Hundred Crack Punch",
    "Rock Breaker", "Crag Breaker", "Vajra Fist", "Arhat Fist", "Tai Chi Fist",
    "Bagua Fist", "Xingyi Fist", "Baji Fist", "Wing Chun Fist", "Hung Fist",
    "Mantis Fist", "Snake Fist", "Tiger Fist", "Dragon Fist", "Leopard Fist",
    "Crane Fist", "Lion Fist", "Monkey Fist", "Drunken Fist", "Soft Palm",
    "Iron Sand Palm", "Heart Destroyer Palm", "Five Poison Palm", "Ice Palm", "Fire Palm",
    "Thunder Palm", "Purple Lightning Palm", "Azure Palm", "Dark Palm", "Cloud Push Palm",
    "Wind God Leg", "Thunder God Leg", "Lightning God Leg", "Snow God Leg", "Ice God Leg",
    "Flame Leg", "Earth Splitter Leg", "Heaven Breaker Leg", "Heaven Scar Leg", "Shadowless Kick",
    "Mandarin Duck Leg", "Soul Hook Leg", "Throat Lock Leg", "Soul Cutter Leg", "Death Seeker Leg",
    "Wind Chaser Leg", "Lightning Leg", "Flame Leg", "Ice Leg", "Golden Bell Shield",
    "Iron Cloth Armor", "Indestructible Body", "Thirteen Champions", "Mixed Origin Kung", "Yijin Jing",
    "Xisui Jing", "Nine Yang Divine", "Nine Yin True", "Beiming Divine", "Star Absorbing",
    "Hua Gong", "Small 无xiang", "Six Yang", "Eight Wastes", "、独孤九剑",
    "辟邪剑法", "葵花宝典", "太极拳", "八卦掌", "形意拳",
    "八极拳", "螳螂拳", "蛇拳", "虎拳", "龙拳",
    "、降龙十八掌", "打狗棒法", "九阴白骨爪", "六脉神剑", "一阳指",
    "弹指神通", "铁砂掌", "金钟罩", "铁布衫", "蛤蟆功",
    "一苇渡江", "梯云纵", "凌波微步", "北冥神功", "吸星大法",
    "化骨绵掌", "绵里藏针", "天外飞仙", "独孤九剑", "辟邪剑法",
    "、太极拳法", "八卦掌", "形意拳", "八极拳", "太极拳",
    "降龙十八掌", "打狗棒法", "九阴白骨爪", "六脉神剑", "一阳指",
    "弹指神通", "铁砂掌", "金钟罩", "铁布衫", "蛤蟆功",
    "一苇渡江", "梯云纵", "凌波微步", "北冥神功", "吸星大法",
    "化骨绵掌", "绵里藏针", "天外飞仙", "独孤九剑", "辟邪剑法",
    "、太极拳法", "八卦掌", "形意拳", "八极拳", "太极拳",
    "降龙十八掌", "打狗棒法", "九阴白骨爪", "六脉神剑", "一阳指",
    "弹指神通", "铁砂掌", "金钟罩", "铁布衫", "蛤蟆功",
    "一苇渡江", "梯云纵", "凌波微步", "北冥神功", "吸星大法",
    "化骨绵掌", "绵里藏针", "天外飞仙", "独孤九剑", "辟邪剑法",
    "、太极拳法", "八卦掌", "形意拳", "八极拳", "太极拳",
    "降龙十八掌", "打狗棒法", "九阴白骨爪", "六脉神剑", "一阳指",
    "弹指神通", "铁砂掌", "金钟罩", "铁布衫", "蛤蟆功",
    "一苇渡江", "梯云纵", "凌波微步", "北冥神功", "吸星大法",
    "化骨绵掌", "绵里藏针", "天外飞仙", "独孤九剑", "辟邪剑法",
    "、太极拳法", "八卦掌", "形意拳", "八极拳", "太极拳",
    "降龙十八掌", "打狗棒法", "九阴白骨爪", "六脉神剑", "一阳指",
    "弹指神通", "铁砂掌", "金钟罩", "铁布衫", "蛤蟆功",
    "一苇渡江", "梯云纵", "凌波微步", "北冥神功", "吸星大法",
    "化骨绵掌", "绵里藏针", "天外飞仙", "独孤九剑", "辟邪剑法",
    "、太极拳法", "八卦掌", "形意拳", "八极拳", "太极拳",
    "降龙十八掌", "打狗棒法", "九阴白骨爪", "六脉神剑", "一阳指",
    "弹指神通", "铁砂掌", "金钟罩", "铁布衫", "蛤蟆功"
]

print(f"English moves count: {len(en_moves)}")
print(f"Chinese moves 105-255 count: {len(cn_moves_105_255)}")
